backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "media/image" # Media files will be stored in the repo under images/uploads

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true

collections:
  - label: "Configuration"
    name: "configuration"   
    files:
      - name: "contact"
        label: "Contact"
        editor:
          preview: false
        file: "_data/contact.json"
        fields:
              - { label: "Téléphone", name: "telephone", widget: "string" }
              - { label: "Email : Principal", name: "mailMain", widget: "string" }
              - { label: "Email : Art", name: "mailArt", widget: "string" }
              - { label: "URL Instagram : Principal", name: "instagram", widget: "string" }
              - { label: "URL Instagram : La main bleue", name: "instagramBleue", widget: "string" }
      - name: "accueil"
        label: "Page d'accueil"
        editor:
          preview: false
        file: "_data/accueil.json"
        fields:
              - { label: "Baseline ligne 1", name: "baseline1", widget: "string" }
              - { label: "Baseline ligne 2", name: "baseline2", widget: "string" }
  # Our blog posts
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Anonymous" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
  # Our pages e.g. About
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: false # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Body", name: "body", widget: "markdown" }
  # Pages Maintenance
  - name: "maintenance"
    label: "Maintenance"
    folder: "collection-cms/maintenance"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Intro ligne 1", name: "intro1", widget: "string" }
      - { label: "Intro ligne 2", name: "intro2", widget: "string" }
      - { label: "Intro contact", name: "contactIntro", widget: "string" }
      - { label: "Info téléphone", name: "infoTelephone", widget: "string" }
      - { label: "Téléphone", name: "telephone", widget: "string" }
      - { label: "Téléphone (sans espace)", name: "telephoneHref", widget: "string" }
      - { label: "Info mail", name: "infoMail", widget: "string" }
      - { label: "Mail", name: "mail", widget: "string" }
  # Pages Art
  - name: "art"
    label: "Art"
    folder: "collection-cms/art"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Intro", name: "intro", widget: "string" }
      - label: "Exemple réalisation"
        name: "exempleRealisation"
        widget: "list"
        allow_add: true
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "Photo", name: "photo", widget: "image", required: false }
          - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Projet futur", name: "introProjet", widget: "string" }
      - { label: "A propos", name: "introAPropos", widget: "string" }
      - { label: "Contact", name: "introContact", widget: "string" }
