backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "media/image/upload" # Media files will be stored in the repo

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true

collections:
  # Contact
  - name: "general"
    label: "Général"
    files:
    - name: "contact"
      label: "Contact"
      editor:
        preview: false
      file: "_data/contact.json"
      fields:
        - { label: "Téléphone", name: "telephone", widget: "string", hint: 'Mettre des espaces pour une meilleure lisibilité' }
        - name: bleue
          label: La main bleue
          widget: 'object'
          fields:
            - { label: "Email", name: "mail", widget: "string" }
            - { label: "Instagram", name: "instagram", widget: "string" }
        - name: mtl
          label: Marion Tampon-lajarriette
          widget: 'object'
          fields:
            - { label: "Email", name: "mail", widget: "string" }
            - { label: "Instagram", name: "instagram", widget: "string" }
  # Accueil
  - label: "Accueil"
    name: "accueil"   
    files:
      - name: "accueil"
        label: "Page d'accueil"
        editor:
          preview: false
        file: "_data/accueil.json"
        fields:
              - { label: "Baseline ligne 1", name: "baseline1", widget: "string" }
              - { label: "Baseline ligne 2", name: "baseline2", widget: "string" }
    # Massage
  - label: "Massage"
    name: "massage"   
    files:
      # Introduction
      - name: "introduction"
        label: "Introduction"
        editor:
          preview: false
        file: "_data/massage/introduction.json"
        fields:
              - { label: "Citation", name: "citation", widget: "text" }
              - { label: "Introduction", name: "introduction", widget: "markdown", modes: ["rich_text"], buttons: ["bold","italic","link","quote","bulleted-list","numbered-list"], editor_components: [] }
              - { label: "Image", name: "image", widget: "image", choose_url: false }
      # Durée & Tarifs
      - name: "tarif"
        label: "Durée & Tarifs"
        editor:
          preview: false
        file: "_data/massage/tarif.json"
        description: 'demo description'
        fields:
          - name: informations
            label: Informations
            label_singular: 'Information'
            widget: list
            fields:
              - { label: "Titre", name: "titre", widget: "string" }
              - { label: "Texte", name: "texte", widget: "markdown", modes: ["rich_text"], buttons: ["bold","italic","link","quote","bulleted-list","numbered-list"], editor_components: [] }
      # Prendre un rendez-vous
      - name: "prendreRdv"
        label: "Prendre un rendez-vous"
        editor:
          preview: false
        file: "_data/massage/prendreRdv.json"
        fields:
              - { label: "Phrase 1", name: "p1", widget: "text" }
              - { label: "Phrase 2", name: "p2", widget: "text" }
              - { label: "Phrase 3", name: "p3", widget: "text" }
  # Our blog posts
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Anonymous" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
