backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "media/image/upload" # Media files will be stored in the repo

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true

collections:
  # Contact
  - name: "general"
    label: "Général"
    files:
    - name: "contact"
      label: "Contact"
      editor:
        preview: false
      file: "_data/contact.json"
      fields:
        - { label: "Téléphone", name: "telephone", widget: "string", hint: 'Mettre des espaces pour une meilleure lisibilité' }
        - name: bleue
          label: La main bleue
          widget: 'object'
          fields:
            - { label: "Email", name: "mail", widget: "string" }
            - { label: "Instagram", name: "instagram", widget: "string" }
        - name: mtl
          label: Marion Tampon-lajarriette
          widget: 'object'
          fields:
            - { label: "Email", name: "mail", widget: "string" }
            - { label: "Instagram", name: "instagram", widget: "string" }
  # Accueil
  - label: "Accueil"
    name: "accueil"   
    files:
      - name: "accueil"
        label: "Page d'accueil"
        editor:
          preview: false
        file: "_data/accueil.json"
        fields:
              - { label: "Baseline ligne 1", name: "baseline1", widget: "string" }
              - { label: "Baseline ligne 2", name: "baseline2", widget: "string" }
    # Massage
  - label: "Massage"
    name: "massage"   
    files:
      # Introduction
      - name: "introduction"
        label: "Introduction"
        editor:
          preview: false
        file: "_data/massage/introduction.json"
        fields:
              - { label: "Citation", name: "citation", widget: "text" }
              - { label: "Introduction", name: "introduction", widget: "markdown", modes: ["rich_text"], buttons: ["bold","italic","link","quote","bulleted-list","numbered-list"], editor_components: [] }
              - { label: "Image", name: "image", widget: "image", choose_url: false }
      # Durée & Tarifs
      - name: "tarif"
        label: "Durée & Tarifs"
        editor:
          preview: false
        file: "_data/massage/tarif.json"
        fields:
          # Carte
          - name: cartes
            label: Cartes
            label_singular: 'Carte'
            widget: list
            max: 4
            summary: '{{fields.titre}}'
            fields:
              - { label: "Image", name: "image", widget: "image", choose_url: false }
              - { label: "Titre", name: "titre", widget: "string" }
              - { label: "Tarifs", name: "tarifs", label_singular: 'Tarif', widget: list, fields: 
                    [
                      { label: "Durée", name: "duree", widget: "string" },
                      { label: "Prix", name: "prix", widget: "string" }
                    ]
                }
              - { label: "Information complémentaire", name: "information", widget: "string", required: false }
              - { label: "Label du lien", name: "lienLabel", widget: "string" }
              - { label: "URL", name: "lienHref", widget: "string", hint: "Laissez vide pour l'email" , required: false }
          # Information complémentaire
          - name: informations
            label: Informations
            label_singular: 'Information'
            widget: list
            summary: '{{fields.titre}}'
            fields:
              - { label: "Image", name: "image", widget: "image", choose_url: false }
              - { label: "Titre", name: "titre", widget: "string" }
              - { label: "Texte", name: "texte", widget: "markdown", modes: ["rich_text"], buttons: ["bold","italic","link","quote","bulleted-list","numbered-list"], editor_components: [] }
      # Types de massages
      - name: "typesMassages"
        label: "Types de massages"
        editor:
          preview: false
        file: "_data/massage/typesMassages.json"
        fields:
              - { label: "Image", name: "image", widget: "image", choose_url: false }
              - { label: "Introduction", name: "introduction", widget: "markdown", modes: ["rich_text"], buttons: ["bold","italic","link","quote","bulleted-list","numbered-list"], editor_components: [] }
              - { label: "Cartes", name: "cartes", label_singular: 'Carte', widget: list, summary: '{{fields.titre}}', fields: 
                    [
                      { label: "Image", name: "image", widget: "image", choose_url: false },
                      { label: "Titre", name: "titre", widget: "string" },
                      { label: "Texte", name: "information", widget: "text", hint: "Balise HTML pris en compte" },
                      { label: "Label du lien", name: "lienLabel", widget: "string" },
                      { label: "URL", name: "lienHref", widget: "string", hint: "Laissez vide pour l'email" , required: false }
                    ]
                }
      # Mon approche
      - name: "monApproche"
        label: "Mon approche"
        editor:
          preview: false
        file: "_data/massage/monApproche.json"
        fields:
          - { label: "Image", name: "image", widget: "image", choose_url: false }
          - { label: "Texte", name: "texte", widget: "markdown", modes: ["rich_text"], buttons: ["bold","italic","link","quote","bulleted-list","numbered-list"], editor_components: [] }
          - { label: "Label du lien formation : Fermer", name: "labelCollapse", widget: "string" }
          - { label: "Label du lien formation : Ouvert", name: "labelCollapseExpanded", widget: "string" }
          - { label: "Formations", name: "formations", label_singular: 'Formation', widget: list, summary: '{{fields.annee}} - {{fields.label}}', fields: 
                [
                  { label: "Date", name: "date", widget: "string" },
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Description", name: "description", widget: "text" }
                ]
            }
          - { label: "Image formation", name: "imageCollapse", widget: "image", choose_url: false }
          - { label: "Témoignages", name: "temoignages", label_singular: 'Témoignage', widget: list, summary: '{{fields.nom}}', fields: 
                [
                  { label: "Image", name: "image", widget: "image", choose_url: false },
                  { label: "Citation", name: "contenu", widget: "text" },
                  { label: "Nom", name: "nom", widget: "string" }
                ]
            }
      # Prendre un rendez-vous
      - name: "prendreRdv"
        label: "Prendre un rendez-vous"
        editor:
          preview: false
        file: "_data/massage/prendreRdv.json"
        fields:
              - { label: "Image", name: "image", widget: "image", choose_url: false }
              - { label: "Texte", name: "texte", widget: "markdown", modes: ["rich_text"], buttons: ["bold","italic","link","quote","bulleted-list","numbered-list"], editor_components: [] }
  # Our blog posts
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Anonymous" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
